"""make user_id nullable, add txn_hash, add cv_pct trend_pct

Revision ID: 59e2ec2f3378
Revises: 30289dcfa099
Create Date: 2026-06-16 20:42:37.525705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e2ec2f3378'
down_revision: Union[str, Sequence[str], None] = '30289dcfa099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stability_metrics', sa.Column('cv_pct', sa.Numeric(precision=8, scale=2), nullable=False))
    op.add_column('stability_metrics', sa.Column('trend_pct', sa.Numeric(precision=8, scale=4), nullable=False))
    op.alter_column('stability_metrics', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('stability_metrics', 'trend')
    op.alter_column('statements', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('transactions', sa.Column('txn_hash', sa.String(), nullable=True))
    op.alter_column('transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_transactions_txn_hash'), 'transactions', ['txn_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_txn_hash'), table_name='transactions')
    op.alter_column('transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('transactions', 'txn_hash')
    op.alter_column('statements', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('stability_metrics', sa.Column('trend', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.alter_column('stability_metrics', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('stability_metrics', 'trend_pct')
    op.drop_column('stability_metrics', 'cv_pct')
    # ### end Alembic commands ###
