"""add factor_detail to stability_metrics

Revision ID: 6693a737775c
Revises: d695107997ed
Create Date: 2026-06-17 16:53:04.439633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6693a737775c'
down_revision: Union[str, Sequence[str], None] = 'd695107997ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stability_metrics', sa.Column('factor_detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stability_metrics', 'factor_detail')
    # ### end Alembic commands ###
