"""add authenticity_signals overlap_details to statements

Revision ID: aace62a2f53f
Revises: 6693a737775c
Create Date: 2026-06-17 18:28:05.696256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aace62a2f53f'
down_revision: Union[str, Sequence[str], None] = '6693a737775c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('authenticity_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('statements', sa.Column('has_cross_source_overlap', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('statements', sa.Column('overlap_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('statements', 'balance_check_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statements', 'balance_check_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('statements', 'overlap_details')
    op.drop_column('statements', 'has_cross_source_overlap')
    op.drop_column('statements', 'authenticity_signals')
    # ### end Alembic commands ###
