"""add action_tip and platform_breakdown to stability_metrics

Revision ID: d695107997ed
Revises: 59e2ec2f3378
Create Date: 2026-06-17 01:47:36.803412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd695107997ed'
down_revision: Union[str, Sequence[str], None] = '59e2ec2f3378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stability_metrics', sa.Column('action_tip', sa.Text(), server_default='', nullable=False))
    op.add_column('stability_metrics', sa.Column('platform_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default='{}',nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stability_metrics', 'platform_breakdown')
    op.drop_column('stability_metrics', 'action_tip')
    # ### end Alembic commands ###
